apiVersion: v1
kind: Service
metadata: 
  name: snippetbox-service
spec:
  selector:
    app.kubernetes.io/name: snippetbox
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 9376
  type: NodePort