kind: Service
apiVersion: v1
metadata:
  name: snippetbox-service-load-balancer
  labels:
    app: snippetbox
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: snippetbox
  type: LoadBalancer
  externalIPs:
  - 192.168.0.200